services:
  - name: django-app
    type: web
    runtime: python
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn expenseswebsite.wsgi:application
databases:
  - name: django-db
    plan: free
